# Generated by Django 4.0.1 on 2022-01-31 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destAddr', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('numPeople', models.IntegerField(default=1, null=True)),
                ('isJoinable', models.BooleanField(default=False)),
                ('otherInfo', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Start'), (2, 'Confirmed'), (3, 'Completed')], default=1)),
                ('driverID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverID', to=settings.AUTH_USER_MODEL)),
                ('rideOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rideOwner', to=settings.AUTH_USER_MODEL)),
                ('shareID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('licensePlateNumber', models.CharField(max_length=30, unique=True)),
                ('capacity', models.IntegerField(default=4)),
                ('otherInfo', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='car_owner')),
            ],
        ),
    ]
